// app/sitemap.js

export default function sitemap() {
  const baseUrl = "https://www.pdfmints.com";

  const routes = [
    "/pdf-to-excel-converter",
    "/excel-to-pdf-online",
    "/pdf-to-ppt-converter",
    "/ppt-to-pdf-converter",
    "/html-to-pdf-online",
    "/pdf-to-text-converter",
    "/text-to-pdf-online",
    "/png-to-pdf-converter",
    "/pdf-to-png-converter",
    "/pdf-to-zip-converter",
    "/password-protect-pdf",
    "/remove-pdf-password",
    "/secure-pdf-file",
    "/encrypt-pdf-online",
    "/decrypt-pdf-online",
    "/pdf-privacy-tools",
    "/safe-pdf-editor",
    "/pdf-security-checker",
    "/protect-document-online",
    "/reduce-pdf-file-size",
    "/optimize-pdf-online",
    "/compress-pdf-for-email",
    "/reduce-pdf-size-without-losing-quality",
    "/high-quality-pdf-compressor",
    "/fast-pdf-compression-tool",
    "/pdf-size-reducer-free",
    "/best-pdf-optimizer",
    "/pdf-tools-online",
    "/free-pdf-editor",
    "/merge-pdf-online",
    "/split-pdf-file",
    "/compress-pdf-online",
    "/convert-pdf-to-word",
    "/word-to-pdf-converter",
    "/jpg-to-pdf-online",
    "/pdf-compressor-free",
    "/compress-pdf-to-200kb",
    "/compress-pdf-to-50kb",
    "/compress-pdf-to-150kb",
    "/compress-pdf-to-300kb",
    "/pdf-size-reducer-for-email-attachment",
    "/compress-pdf-to-100kb",
    "/compress-pdf-to-200kb",
    "/compress-pdf-for-email",
    "/compress-pdf-for-whatsapp",
    "/reduce-pdf-size-without-losing-quality",
    "/merge-pdf-files",
    "/merge-pdf-files-online-free",
    "/combine-pdf-online",
    "/join-multiple-pdf-files",
    "/split-pdf-pages",
    "/split-pdf-pages-online",
    "/extract-pages-from-pdf",
    "/password-protect-pdf",
    "/password-protect-pdf-online",
    "/unlock-protect-pdf",
    "/unlock-pdf-online",
    "/lock-pdf-file",
    "/pdf-to-jpg",
    "/pdf-to-jpg-converter",
    "/jpg-to-pdf",
    "/jpg-to-pdf-converter",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route === "" ? 1 : 0.8,
  }));
}
